---
name: pa_rentalcam
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^4.0.5
  google_nav_bar: ^5.0.6
  iconsax: ^0.0.8
  cloud_firestore: ^4.8.1
  firebase_core: ^2.14.0
  intl: ^0.18.1
  firebase_auth: ^4.6.3
  shared_preferences: ^2.2.0
  image_picker: ^1.0.0
  firebase_storage: ^11.2.4

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  lottie: ^2.3.2
flutter:
  uses-material-design: true
  assets:
  - assets/images/
