---
name: pa_rentalcam
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  google_nav_bar: ^5.0.6
  iconsax: ^0.0.8
  cloud_firestore: ^4.8.1
  firebase_core: ^2.14.0
  intl: ^0.18.1
  firebase_auth: ^4.6.3
  shared_preferences: ^2.2.0
  image_picker: ^0.8.9
  flutter_image_compress: ^2.0.3
  firebase_storage: ^11.2.2
  path_provider: ^2.0.15
  equatable: ^2.0.5
  image: ^4.0.17
dev_dependencies:
  flutter_test:
    sdk: flutter
  lottie: ^2.3.2
flutter:
  uses-material-design: true
  assets:
  - assets/images/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_mbgg.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  